<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__wpformsfields1</name>
   <tag></tag>
   <elementGuidId>924c6527-b3cc-45ac-8a95-d7953d951947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wpforms-161-field_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfc82924-3081-43f9-afff-0adffc9b1a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>3c548266-b5c8-444c-ab18-7a9cd6f46927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_1</value>
      <webElementGuid>a2058a18-4a3b-4e55-8aa3-46f384b2721c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required wpforms-error</value>
      <webElementGuid>6525858b-2b14-4ea9-be4c-d87f8fe938d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][1]</value>
      <webElementGuid>4c2daace-8148-4b68-bc5f-907262d891f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b4769c91-1830-4d60-af64-56f74d99b73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_1&quot;)</value>
      <webElementGuid>cb3b93fe-4b02-4571-9d38-218864e41951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wpforms-161-field_1']</value>
      <webElementGuid>6aac0dd0-aece-4b8a-a479-9e3bbacfc024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_1-container']/input</value>
      <webElementGuid>83902fd9-3dec-4577-afdd-2532de76a013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>670c2768-05de-443f-8a20-56ac3f550855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'wpforms-161-field_1' and @name = 'wpforms[fields][1]']</value>
      <webElementGuid>dbc96ea4-e72e-4f26-bc48-180044a2b5b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
