<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__wpformsfields2</name>
   <tag></tag>
   <elementGuidId>730b715e-955c-423a-ba27-07a56dfd030e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#wpforms-161-field_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='wpforms-161-field_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>04268263-825f-44b4-b0ab-663b29a4c717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-161-field_2</value>
      <webElementGuid>5d691649-7aea-4fb3-92a0-d4f100e9daa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-field-medium wpforms-field-required wpforms-error</value>
      <webElementGuid>1352f025-eed8-4299-918f-bef207cb7c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[fields][2]</value>
      <webElementGuid>abea7a74-ba89-4578-a2e2-7352dcda7af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-161-field_2&quot;)</value>
      <webElementGuid>24796216-087d-4dc0-9c4c-d2dcd17e2763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='wpforms-161-field_2']</value>
      <webElementGuid>f5bc39b7-9863-4612-90f2-6e3ae5127c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpforms-161-field_2-container']/textarea</value>
      <webElementGuid>7a1f419e-b53b-484d-afec-4e287b0c0d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6cd8cbc5-758d-45fd-b5f6-dd32a8d61529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'wpforms-161-field_2' and @name = 'wpforms[fields][2]']</value>
      <webElementGuid>f8e81461-0106-4c55-9b8f-75fec41c2d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
